---
# tasks file for virtualenvwrapper

- block:
    - name: install virtualenvwrapper
      apt:
        name: virtualenvwrapper
        state: latest
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
  become: true
  become_user: root
  become_method: sudo
  tags:
    - virtualenvwrapper

