---
# tasks file for git

- block:
    - name: install git
      apt:
        name: git
        state: latest
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
  become: true
  become_user: root
  become_method: sudo
  tags:
    - git

