---
# tasks file for ansible

- block:
    - name: ansible ppa key
      apt_key:
        id: 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
        keyserver: hkp://keyserver.ubuntu.com
        state: present
        
    - name: register ansible ppa
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
        validate_certs: true

    - name: install ansible
      apt:
        name: ansible
        state: latest
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
  become: true
  become_user: root
  become_method: sudo
  tags:
    - ansible
